<?php

namespace common\models;

class Action extends BaseEntity
{

    public static function tableName()
    {
        return 'actions';
    }

    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }
}